name: Track issues with Github project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add new issues to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/Chirag4904/projects/2
          github-token: ${{ secrets.TIMETABLETOKEN }}
